# Dockerfile for using prebuilt binary from GitHub Actions
FROM alpine:3.22

RUN mkdir -p /app
WORKDIR /app

# Copy the prebuilt binary
COPY dist/server-linux-amd64 /app/OJ_API

RUN chmod +x /app/OJ_API

# Expose port 3001 to the outside world
EXPOSE 3001

# Command to run the executable
ENTRYPOINT ["/app/OJ_API"]
