// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/gitea": {
            "post": {
                "description": "Receive Gitea hook",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitea"
                ],
                "summary": "Receive Gitea hook",
                "parameters": [
                    {
                        "description": "Gitea Hook",
                        "name": "hook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.WebhookPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.ResponseHTTP"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "type": {
                                            "$ref": "#/definitions/handlers.WebhookPayload"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/gitea/auth": {
            "post": {
                "description": "Use basic authentication to access the Gitea API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitea"
                ],
                "summary": "Use basic authentication to access the Gitea API",
                "parameters": [
                    {
                        "description": "Basic Authentication",
                        "name": "BasicAuthentication",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicAuthentication"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Return access token",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResponseHTTP"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/api/gitea/question/{question_id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Take a question and create a repository in Gitea",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitea"
                ],
                "summary": "Take a question and create a repository in Gitea",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "question_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/api/gitea/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get User Profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitea"
                ],
                "summary": "Get User Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.ResponseHTTP"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/gitea.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/api/gitea/user/bulk": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Bulk create User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gitea"
                ],
                "summary": "Bulk create User",
                "parameters": [
                    {
                        "description": "Username + Email Domain =\u003e username1@example.com",
                        "name": "Usernames",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.BulkCreateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Return successful and failed users",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.ResponseHTTP"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.BulkCreateUserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/api/question": {
            "get": {
                "description": "Get a list of questions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "Get a list of questions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number of results to return (1-based)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size of results. Default is 10.",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.ResponseHTTP"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handlers.GetQuestionListResponseData"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/api/question/id/{ID}": {
            "get": {
                "description": "Retrieve only public questions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "Get a question by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the Question to get",
                        "name": "ID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.ResponseHTTP"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.GetQuestionResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/api/question/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of questions by user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "Get a list of questions by user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number of results to return (1-based)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size of results. Default is 10.",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.ResponseHTTP"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handlers.GetUsersQuestionsResponseData"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/api/question/user/id/{ID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a specific question associated with a user by its Question ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "Get a user's question by Question ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the Question to get",
                        "name": "ID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.ResponseHTTP"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.GetUserQuestionResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/api/question/{UQR_ID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a question by UQR_ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "Get a question by UQR_ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the UserQuestionRelation to get",
                        "name": "UQR_ID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.ResponseHTTP"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.GetQuestionResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/api/sandbox": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Specify the shell command for the corresponding repo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sandbox"
                ],
                "summary": "Specify the shell command for the corresponding repo",
                "parameters": [
                    {
                        "description": "Shell command",
                        "name": "cmd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.Sandbox"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.ResponseHTTP"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.QuestionTestScript"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/api/sandbox/status": {
            "get": {
                "description": "Get the current available sandbox count and waiting count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sandbox"
                ],
                "summary": "Get the current available sandbox count and waiting count",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.ResponseHTTP"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.StatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/score": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a score by repo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Score"
                ],
                "summary": "Get a score by repo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of the repo",
                        "name": "owner",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of the repo",
                        "name": "repo",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page number of results to return (1-based)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size of results. Default is 10.",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.ResponseHTTP"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.GetScoreResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/api/score/question/{question_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a score by question ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Score"
                ],
                "summary": "Get a score by question ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "question ID",
                        "name": "question_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page number of results to return (1-based)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size of results. Default is 10.",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.ResponseHTTP"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.Score"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/api/score/rescore/{question_id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Re-score a question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Score"
                ],
                "summary": "Re-score a question",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "question ID",
                        "name": "question_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/api/score/{UQR_ID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a score by UQR ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Score"
                ],
                "summary": "Get a score by UQR ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UQR ID",
                        "name": "UQR_ID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page number of results to return (1-based)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size of results. Default is 10.",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.ResponseHTTP"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.Score"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        }
    },
    "definitions": {
        "gitea.Commit": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/gitea.User"
                },
                "commit": {
                    "$ref": "#/definitions/gitea.RepoCommit"
                },
                "committer": {
                    "$ref": "#/definitions/gitea.User"
                },
                "created": {
                    "type": "string"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gitea.CommitAffectedFiles"
                    }
                },
                "html_url": {
                    "type": "string"
                },
                "parents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gitea.CommitMeta"
                    }
                },
                "sha": {
                    "type": "string"
                },
                "stats": {
                    "$ref": "#/definitions/gitea.CommitStats"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "gitea.CommitAffectedFiles": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                }
            }
        },
        "gitea.CommitMeta": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "sha": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "gitea.CommitStats": {
            "type": "object",
            "properties": {
                "additions": {
                    "type": "integer"
                },
                "deletions": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "gitea.CommitUser": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "gitea.ExternalTracker": {
            "type": "object",
            "properties": {
                "external_tracker_format": {
                    "description": "External Issue Tracker URL Format. Use the placeholders {user}, {repo} and {index} for the username, repository name and issue index.",
                    "type": "string"
                },
                "external_tracker_style": {
                    "description": "External Issue Tracker Number Format, either ` + "`" + `numeric` + "`" + ` or ` + "`" + `alphanumeric` + "`" + `",
                    "type": "string"
                },
                "external_tracker_url": {
                    "description": "URL of external issue tracker.",
                    "type": "string"
                }
            }
        },
        "gitea.ExternalWiki": {
            "type": "object",
            "properties": {
                "external_wiki_url": {
                    "description": "URL of external wiki.",
                    "type": "string"
                }
            }
        },
        "gitea.InternalTracker": {
            "type": "object",
            "properties": {
                "allow_only_contributors_to_track_time": {
                    "description": "Let only contributors track time (Built-in issue tracker)",
                    "type": "boolean"
                },
                "enable_issue_dependencies": {
                    "description": "Enable dependencies for issues and pull requests (Built-in issue tracker)",
                    "type": "boolean"
                },
                "enable_time_tracker": {
                    "description": "Enable time tracking (Built-in issue tracker)",
                    "type": "boolean"
                }
            }
        },
        "gitea.MergeStyle": {
            "type": "string",
            "enum": [
                "merge",
                "rebase",
                "rebase-merge",
                "squash"
            ],
            "x-enum-varnames": [
                "MergeStyleMerge",
                "MergeStyleRebase",
                "MergeStyleRebaseMerge",
                "MergeStyleSquash"
            ]
        },
        "gitea.PayloadCommitVerification": {
            "type": "object",
            "properties": {
                "payload": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "verified": {
                    "type": "boolean"
                }
            }
        },
        "gitea.Permission": {
            "type": "object",
            "properties": {
                "admin": {
                    "type": "boolean"
                },
                "pull": {
                    "type": "boolean"
                },
                "push": {
                    "type": "boolean"
                }
            }
        },
        "gitea.RepoCommit": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/gitea.CommitUser"
                },
                "committer": {
                    "$ref": "#/definitions/gitea.CommitUser"
                },
                "message": {
                    "type": "string"
                },
                "tree": {
                    "$ref": "#/definitions/gitea.CommitMeta"
                },
                "url": {
                    "type": "string"
                },
                "verification": {
                    "$ref": "#/definitions/gitea.PayloadCommitVerification"
                }
            }
        },
        "gitea.Repository": {
            "type": "object",
            "properties": {
                "allow_merge_commits": {
                    "type": "boolean"
                },
                "allow_rebase": {
                    "type": "boolean"
                },
                "allow_rebase_explicit": {
                    "type": "boolean"
                },
                "allow_squash_merge": {
                    "type": "boolean"
                },
                "archived": {
                    "type": "boolean"
                },
                "avatar_url": {
                    "type": "string"
                },
                "clone_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "default_branch": {
                    "type": "string"
                },
                "default_merge_style": {
                    "$ref": "#/definitions/gitea.MergeStyle"
                },
                "description": {
                    "type": "string"
                },
                "empty": {
                    "type": "boolean"
                },
                "external_tracker": {
                    "$ref": "#/definitions/gitea.ExternalTracker"
                },
                "external_wiki": {
                    "$ref": "#/definitions/gitea.ExternalWiki"
                },
                "fork": {
                    "type": "boolean"
                },
                "forks_count": {
                    "type": "integer"
                },
                "full_name": {
                    "type": "string"
                },
                "has_actions": {
                    "type": "boolean"
                },
                "has_issues": {
                    "type": "boolean"
                },
                "has_packages": {
                    "type": "boolean"
                },
                "has_projects": {
                    "type": "boolean"
                },
                "has_pull_requests": {
                    "type": "boolean"
                },
                "has_releases": {
                    "type": "boolean"
                },
                "has_wiki": {
                    "type": "boolean"
                },
                "html_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ignore_whitespace_conflicts": {
                    "type": "boolean"
                },
                "internal": {
                    "type": "boolean"
                },
                "internal_tracker": {
                    "$ref": "#/definitions/gitea.InternalTracker"
                },
                "mirror": {
                    "type": "boolean"
                },
                "mirror_interval": {
                    "type": "string"
                },
                "mirror_updated": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "open_issues_count": {
                    "type": "integer"
                },
                "open_pr_counter": {
                    "type": "integer"
                },
                "original_url": {
                    "type": "string"
                },
                "owner": {
                    "$ref": "#/definitions/gitea.User"
                },
                "parent": {
                    "$ref": "#/definitions/gitea.Repository"
                },
                "permissions": {
                    "$ref": "#/definitions/gitea.Permission"
                },
                "private": {
                    "type": "boolean"
                },
                "release_counter": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "ssh_url": {
                    "type": "string"
                },
                "stars_count": {
                    "type": "integer"
                },
                "template": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                },
                "watchers_count": {
                    "type": "integer"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "gitea.User": {
            "type": "object",
            "properties": {
                "active": {
                    "description": "Is user active",
                    "type": "boolean"
                },
                "avatar_url": {
                    "description": "URL to the user's avatar",
                    "type": "string"
                },
                "created": {
                    "description": "Date and Time of user creation",
                    "type": "string"
                },
                "description": {
                    "description": "the user's description",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "followers_count": {
                    "description": "user counts",
                    "type": "integer"
                },
                "following_count": {
                    "type": "integer"
                },
                "full_name": {
                    "description": "the user's full name",
                    "type": "string"
                },
                "id": {
                    "description": "the user's id",
                    "type": "integer"
                },
                "is_admin": {
                    "description": "Is the user an administrator",
                    "type": "boolean"
                },
                "language": {
                    "description": "User locale",
                    "type": "string"
                },
                "last_login": {
                    "description": "Date and Time of last login",
                    "type": "string"
                },
                "location": {
                    "description": "the user's location",
                    "type": "string"
                },
                "login": {
                    "description": "the user's username",
                    "type": "string"
                },
                "login_name": {
                    "description": "The login_name of non local users (e.g. LDAP / OAuth / SMTP)",
                    "type": "string"
                },
                "prohibit_login": {
                    "description": "Is user login prohibited",
                    "type": "boolean"
                },
                "restricted": {
                    "description": "Is user restricted",
                    "type": "boolean"
                },
                "source_id": {
                    "description": "The ID of the Authentication Source for non local users.",
                    "type": "integer"
                },
                "starred_repos_count": {
                    "type": "integer"
                },
                "visibility": {
                    "description": "User visibility level option",
                    "allOf": [
                        {
                            "$ref": "#/definitions/gitea.VisibleType"
                        }
                    ]
                },
                "website": {
                    "description": "the user's website",
                    "type": "string"
                }
            }
        },
        "gitea.VisibleType": {
            "type": "string",
            "enum": [
                "public",
                "limited",
                "private"
            ],
            "x-enum-varnames": [
                "VisibleTypePublic",
                "VisibleTypeLimited",
                "VisibleTypePrivate"
            ]
        },
        "handlers.BasicAuthentication": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "username": {
                    "type": "string",
                    "example": "username"
                }
            }
        },
        "handlers.BulkCreateUser": {
            "type": "object",
            "required": [
                "default_password",
                "email_domain",
                "usernames"
            ],
            "properties": {
                "default_password": {
                    "type": "string",
                    "example": "password"
                },
                "email_domain": {
                    "type": "string",
                    "example": "example.com"
                },
                "usernames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "username1",
                        "username2"
                    ]
                }
            }
        },
        "handlers.BulkCreateUserResponse": {
            "type": "object",
            "properties": {
                "failed_users": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "username1": "error"
                    }
                },
                "successful_users": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "username1"
                    ]
                }
            }
        },
        "handlers.GetQuestionListResponseData": {
            "type": "object",
            "required": [
                "question_count",
                "questions"
            ],
            "properties": {
                "question_count": {
                    "type": "integer"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Question"
                    }
                }
            }
        },
        "handlers.GetQuestionResponseData": {
            "type": "object",
            "required": [
                "description",
                "git_repo_url",
                "parent_git_repo_url",
                "readme",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "git_repo_url": {
                    "type": "string"
                },
                "parent_git_repo_url": {
                    "type": "string"
                },
                "readme": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "handlers.GetScoreResponseData": {
            "type": "object",
            "required": [
                "scores",
                "scores_count"
            ],
            "properties": {
                "scores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.Score"
                    }
                },
                "scores_count": {
                    "type": "integer"
                }
            }
        },
        "handlers.GetUserQuestionResponseData": {
            "type": "object",
            "required": [
                "description",
                "git_repo_url",
                "parent_git_repo_url",
                "readme",
                "title",
                "uqr_id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "git_repo_url": {
                    "type": "string"
                },
                "parent_git_repo_url": {
                    "type": "string"
                },
                "readme": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "uqr_id": {
                    "type": "integer"
                }
            }
        },
        "handlers.GetUsersQuestionsResponseData": {
            "type": "object",
            "required": [
                "question",
                "question_count"
            ],
            "properties": {
                "question": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers._GetUsersQuestionsResponseData"
                    }
                },
                "question_count": {
                    "type": "integer"
                }
            }
        },
        "handlers.ResponseHTTP": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.Sandbox": {
            "type": "object",
            "required": [
                "script",
                "source_git_url"
            ],
            "properties": {
                "script": {
                    "type": "string",
                    "example": "#!/bin/bash\n\necho 'Hello, World!'"
                },
                "source_git_url": {
                    "type": "string",
                    "example": "user_name/repo_name"
                }
            }
        },
        "handlers.Score": {
            "type": "object",
            "required": [
                "judge_time",
                "message",
                "score"
            ],
            "properties": {
                "judge_time": {
                    "type": "string",
                    "example": "2021-07-01T00:00:00Z"
                },
                "message": {
                    "type": "string",
                    "example": "Scored successfully"
                },
                "score": {
                    "type": "number",
                    "example": 100
                }
            }
        },
        "handlers.StatusResponse": {
            "type": "object",
            "properties": {
                "available_count": {
                    "type": "integer"
                },
                "processing_count": {
                    "type": "integer"
                },
                "waiting_count": {
                    "type": "integer"
                }
            }
        },
        "handlers.WebhookPayload": {
            "type": "object",
            "properties": {
                "after": {
                    "type": "string"
                },
                "before": {
                    "type": "string"
                },
                "commits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gitea.Commit"
                    }
                },
                "compare_url": {
                    "type": "string"
                },
                "pusher": {
                    "$ref": "#/definitions/gitea.User"
                },
                "ref": {
                    "type": "string"
                },
                "repository": {
                    "$ref": "#/definitions/gitea.Repository"
                },
                "sender": {
                    "$ref": "#/definitions/gitea.User"
                }
            }
        },
        "handlers._GetUsersQuestionsResponseData": {
            "type": "object",
            "required": [
                "description",
                "git_repo_url",
                "parent_git_repo_url",
                "q_id",
                "title",
                "uqr_id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "git_repo_url": {
                    "type": "string"
                },
                "parent_git_repo_url": {
                    "type": "string"
                },
                "q_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "uqr_id": {
                    "type": "integer"
                }
            }
        },
        "models.Question": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "gitRepoURL": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.QuestionTestScript": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "question": {
                    "$ref": "#/definitions/models.Question"
                },
                "questionID": {
                    "type": "integer"
                },
                "testScript": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "OJ-PoC API",
	Description:      "This is a simple OJ-PoC API server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
